Observable("test1")
  .concatWith(
    Observable.zip(Observable("test2"), Observable("test3"), Observable("test4"))
      .map(_ => _.concat(_))
  )
  .concatWith(Observable("test5"), Observable("test6"))
  .skip(1)
  .take(2)
  .tap(console.log)
  .subscribe()
